### PR TITLE
Add VS2017 support

### PR DESCRIPTION
**Pull request by sclarke81**
I've added support for VS2017. I've tested it on VS2017 Pro only though so we'd need to confirm VS2015 support hasn't been broken.

### CODE REVIEW

**Comment by cyotek** [comment]
Thanks for taking the time to upgrade the solution. I can't tell offhand whether or not this will break VS2015, but as I do have both 2015 and 2017 installed I'll compile and test locally - probably won't be until the weekend before I have time though. Assuming it works, I'll get it merged and an updated VSIX pushed to the gallery.

Thanks!

Regards;
Richard Moss

**Comment by sclarke81** [comment]
No problem. Thanks for making the extension available - I made use of it today.

Let me know if it doesn't work and there's anything you'd like me to do.

Cheers,

Stephen

_Sent from my Motorola Nexus 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by cyotek** [comment]
Hello,

Just to let you know I haven't forgotten about this PR! I tested it this morning but unfortunately it has completely broken in VS2015 due to referencing `Microsoft.VisualStudio.Shell.15.0`. I'll have a play and see if I can work around it (maybe if I just change the manifest to be explicit about 2017 that'll be enough)

Regards;
Richard Moss

**Comment by sclarke81** [comment]
That's fine. Sorry I wasn't able to test it in 2015. Thanks for the update though.

_Sent from my Google Nexus 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by cyotek** [comment]
Hello,

I've added separate solution and project files for VS2017 support rather than trying to do them both from the same solution, I just haven't got time to try right now to figure out how to make them coexist and I think I've delayed getting _something_ done for long enough. So unfortunately I wasn't able to use this PR as it stands.

Once again, thanks for the contribution, I'm sorry I wasn't able to make use of it in the end.

**Comment by cyotek** [comment]
I'd forgotten there wasn't an issue associated with this PR so I hadn't included any more detail above. You can grab a version that works with VS2017 from [here](https://marketplace.visualstudio.com/items?itemName=RichardJMoss.AddExistingProjects-19444). Due to the issues I had with VS2017 breaking VS2015 extensions, I've decided to make my life simpler and just publish it as a separate extension.

Apologies for how long it took to get this done.

Regards;
Richard Moss

**Pull request closed without merging**
